### ISSUE TITLE
Incorrect example config

### ISSUE THREAD

**Issue by vwildi** [DrDynamic/dotbot-snap#4]
The example config in the `README.md` uses incorrect syntax, which causes that the specified snaps will not be installed. Due to the AttributeError: 'list' object has no attribute 'items'
The problem is that Python interprets the data as list, not as dictionary, and lists do not implement the items() method.

The correct syntax would be as follows:
```yaml
- defaults:
    snap:
      classic: false # default
...
- snap:
    bpytop:
    chromium:
    mailspring:
    node:
        classic: true
    ...
...
```
